/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package burgerShop;

/**
 *
 * @author Prof
 */
public class Shop extends javax.swing.JFrame {

    /**
     * Creates new form Shop
     */
    public Shop() {
        initComponents();
        getDefaultBehavior();
    }

    public void getDefaultBehavior() {
        initialize();
        hideBurgerOptions();
        hideDrinkOptions();
        checkDrink();
        hideDessertOptions();
        checkDessert();
        checkActions();
        resetPrice();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOptions = new javax.swing.JPanel();
        chkBurger = new javax.swing.JCheckBox();
        pnlBurger = new javax.swing.JPanel();
        cbxBurger = new javax.swing.JComboBox();
        chkCheese = new javax.swing.JCheckBox();
        chkFrenchFries = new javax.swing.JCheckBox();
        chkDrink = new javax.swing.JCheckBox();
        pnlDrink = new javax.swing.JPanel();
        cbxDrink = new javax.swing.JComboBox();
        cbxDrinkDetail = new javax.swing.JComboBox();
        chkDessert = new javax.swing.JCheckBox();
        cbxDessert = new javax.swing.JComboBox();
        pnlActions = new javax.swing.JPanel();
        btnNewOrder = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        lblPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlOptions.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        chkBurger.setText("Burger");
        chkBurger.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkBurgerItemStateChanged(evt);
            }
        });

        cbxBurger.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ham", "Chicken", "Fish" }));
        cbxBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBurgerActionPerformed(evt);
            }
        });

        chkCheese.setText("Cheese");

        javax.swing.GroupLayout pnlBurgerLayout = new javax.swing.GroupLayout(pnlBurger);
        pnlBurger.setLayout(pnlBurgerLayout);
        pnlBurgerLayout.setHorizontalGroup(
            pnlBurgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBurgerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chkCheese)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        pnlBurgerLayout.setVerticalGroup(
            pnlBurgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBurgerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBurgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkCheese))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        chkFrenchFries.setText("French Fries");
        chkFrenchFries.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkFrenchFriesItemStateChanged(evt);
            }
        });

        chkDrink.setText("Drink");
        chkDrink.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkDrinkItemStateChanged(evt);
            }
        });

        cbxDrink.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Beverage", "IceTea" }));
        cbxDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDrinkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDrinkLayout = new javax.swing.GroupLayout(pnlDrink);
        pnlDrink.setLayout(pnlDrinkLayout);
        pnlDrinkLayout.setHorizontalGroup(
            pnlDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDrinkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxDrinkDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        pnlDrinkLayout.setVerticalGroup(
            pnlDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDrinkLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDrinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxDrinkDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        chkDessert.setText("Dessert");
        chkDessert.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkDessertItemStateChanged(evt);
            }
        });

        cbxDessert.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ice Cream", "Donnuts" }));

        javax.swing.GroupLayout pnlOptionsLayout = new javax.swing.GroupLayout(pnlOptions);
        pnlOptions.setLayout(pnlOptionsLayout);
        pnlOptionsLayout.setHorizontalGroup(
            pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOptionsLayout.createSequentialGroup()
                        .addComponent(chkBurger)
                        .addGap(18, 18, 18)
                        .addComponent(pnlBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chkFrenchFries)
                    .addGroup(pnlOptionsLayout.createSequentialGroup()
                        .addComponent(chkDrink)
                        .addGap(18, 18, 18)
                        .addComponent(pnlDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlOptionsLayout.createSequentialGroup()
                        .addComponent(chkDessert)
                        .addGap(18, 18, 18)
                        .addComponent(cbxDessert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlOptionsLayout.setVerticalGroup(
            pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOptionsLayout.createSequentialGroup()
                .addGroup(pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlOptionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chkBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(chkFrenchFries)
                .addGap(18, 18, 18)
                .addGroup(pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDrink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkDrink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkDessert)
                    .addComponent(cbxDessert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlActions.setBorder(javax.swing.BorderFactory.createTitledBorder("Actions"));

        btnNewOrder.setText("New Order");
        btnNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOrderActionPerformed(evt);
            }
        });

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        lblPrice.setText("Price:");

        javax.swing.GroupLayout pnlActionsLayout = new javax.swing.GroupLayout(pnlActions);
        pnlActions.setLayout(pnlActionsLayout);
        pnlActionsLayout.setHorizontalGroup(
            pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNewOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalculate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPrice)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlActionsLayout.setVerticalGroup(
            pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewOrder)
                    .addComponent(btnCalculate)
                    .addComponent(lblPrice))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlActions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkBurgerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkBurgerItemStateChanged
        // TODO add your handling code here:
        if (chkBurger.isSelected()) {
            showBurgerOptions();
        } else {
            resetBurgerOptions();
            hideBurgerOptions();
            resetDrink();
            resetDessert();
        }
        checkDrink();
        checkDessert();
        checkActions();
    }//GEN-LAST:event_chkBurgerItemStateChanged

    private void cbxBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBurgerActionPerformed
        // TODO add your handling code here:
        resetCheese();
        checkCheese();
    }//GEN-LAST:event_cbxBurgerActionPerformed

    private void chkDrinkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkDrinkItemStateChanged
        // TODO add your handling code here:
        if (chkDrink.isSelected()) {
            resetDrinkOption();
            showDrinkOptions();
        } else {
            hideDrinkOptions();
        }
    }//GEN-LAST:event_chkDrinkItemStateChanged

    private void cbxDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDrinkActionPerformed
        // TODO add your handling code here:
        resetDrinkDetail();
    }//GEN-LAST:event_cbxDrinkActionPerformed

    private void chkDessertItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkDessertItemStateChanged
        // TODO add your handling code here:
        if (chkDessert.isSelected()) {
            showDessertOptions();
        } else {
            resetDessertOptions();
            hideDessertOptions();
        }
    }//GEN-LAST:event_chkDessertItemStateChanged

    private void chkFrenchFriesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkFrenchFriesItemStateChanged
        // TODO add your handling code here:
        checkActions();
    }//GEN-LAST:event_chkFrenchFriesItemStateChanged

    private void btnNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOrderActionPerformed
        // TODO add your handling code here:
        enableOptions();
        resetNewOrder();
    }//GEN-LAST:event_btnNewOrderActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        disableCalculate();
        disableOptions();
        getPrice();
    }//GEN-LAST:event_btnCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shop().setVisible(true);
            }
        });
    }
    
    public void initialize(){
        this.setLocationRelativeTo(this);
        this.setTitle("Best Burger");
    }

    public void showBurgerOptions() {
        pnlBurger.setVisible(true);
    }

    public void hideBurgerOptions() {
        pnlBurger.setVisible(false);
    }

    public void resetBurgerOptions() {
        cbxBurger.setSelectedIndex(0);
    }

    public void resetCheese() {
        chkCheese.setSelected(false);
    }

    public void checkCheese() {
        switch (cbxBurger.getSelectedItem().toString()) {
            case "Fish":
                chkCheese.setEnabled(false);
                break;
            case "Ham":
            case "Chicken":
                chkCheese.setEnabled(true);
                break;

        }
    }

    public void resetDrinkOption() {
        cbxDrink.setSelectedIndex(0);
    }

    public void showDrinkOptions() {
        pnlDrink.setVisible(true);
    }

    public void hideDrinkOptions() {
        pnlDrink.setVisible(false);
    }

    public void resetDrinkDetail() {
        cbxDrinkDetail.removeAllItems();
        switch (cbxDrink.getSelectedItem().toString()) {
            case "Beverage":
                cbxDrinkDetail.addItem("Pepsi");
                cbxDrinkDetail.addItem("7up");
                break;
            case "IceTea":
                cbxDrinkDetail.addItem("Peach");
                cbxDrinkDetail.addItem("Lemon");
                break;
        }
    }

    public void showDessertOptions() {
        cbxDessert.setVisible(true);
    }

    public void hideDessertOptions() {
        cbxDessert.setVisible(false);
    }

    public void resetDessertOptions() {
        cbxDessert.setSelectedIndex(0);
    }

    public void resetDrink() {
        chkDrink.setSelected(false);
    }

    public void resetDessert() {
        chkDessert.setSelected(false);
    }

    public void checkDrink() {
        if (chkBurger.isSelected()) {
            chkDrink.setEnabled(true);
        } else {
            chkDrink.setEnabled(false);
        }
    }

    public void checkDessert() {
        if (chkBurger.isSelected()) {
            chkDessert.setEnabled(true);
        } else {
            chkDessert.setEnabled(false);
        }
    }

    public void checkActions() {
        if (chkBurger.isSelected()
                || chkFrenchFries.isSelected()) {
            btnNewOrder.setEnabled(true);
            btnCalculate.setEnabled(true);
        } else {
            btnNewOrder.setEnabled(false);
            btnCalculate.setEnabled(false);
        }
    }

    public void resetNewOrder() {
        chkBurger.setSelected(false);
        chkFrenchFries.setSelected(false);
        resetPrice();
    }

    public void getPrice() {
        int price = 0;

        if (chkBurger.isSelected()) {
            switch (cbxBurger.getSelectedItem().toString()) {
                case "Ham":
                    price = 9000;
                    break;
                case "Chicken":
                    price = 8000;
                    break;
                case "Fish":
                    price = 7000;
                    break;
            }
            if (chkCheese.isSelected()) {
                price += 1000;
            }
        }
        if (chkFrenchFries.isSelected()) {
            price += 2500;
        }
        if (chkDrink.isSelected()) {
            switch (cbxDrink.getSelectedItem().toString()) {
                case "Beverage":
                    price += 1000;
                    break;
                case "IceTea":
                    price += 1500;
                    break;
            }
        }
        if (chkDessert.isSelected()) {
            switch (cbxDessert.getSelectedItem().toString()) {
                case "Donnuts":
                    price += 2000;
                    break;
                case "IceCream":
                    price += 2500;
                    break;
            }
        }
        if (chkBurger.isSelected() && chkFrenchFries.isSelected()
                && chkDrink.isSelected() && chkDessert.isSelected()) {
            price -= 1500;
        } else if (chkBurger.isSelected() && chkFrenchFries.isSelected()
                && chkDrink.isSelected()) {
            price -= 1000;
        }

        lblPrice.setText(lblPrice.getText() + price);
        lblPrice.setVisible(true);
    }

    public void resetPrice() {
        lblPrice.setText("Price:");
        lblPrice.setVisible(false);
    }

    public void disableOptions() {
        chkBurger.setEnabled(false);
        cbxBurger.setEnabled(false);
        chkCheese.setEnabled(false);
        chkFrenchFries.setEnabled(false);
        chkDrink.setEnabled(false);
        cbxDrink.setEnabled(false);
        cbxDrinkDetail.setEnabled(false);
        chkDessert.setEnabled(false);
        cbxDessert.setEnabled(false);
    }

    public void enableOptions() {
        chkBurger.setEnabled(true);
        cbxBurger.setEnabled(true);
        chkCheese.setEnabled(true);
        chkFrenchFries.setEnabled(true);
        cbxDrink.setEnabled(true);
        cbxDrinkDetail.setEnabled(true);
        cbxDessert.setEnabled(true);
    }
    
    public void disableCalculate(){
        btnCalculate.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnNewOrder;
    private javax.swing.JComboBox cbxBurger;
    private javax.swing.JComboBox cbxDessert;
    private javax.swing.JComboBox cbxDrink;
    private javax.swing.JComboBox cbxDrinkDetail;
    private javax.swing.JCheckBox chkBurger;
    private javax.swing.JCheckBox chkCheese;
    private javax.swing.JCheckBox chkDessert;
    private javax.swing.JCheckBox chkDrink;
    private javax.swing.JCheckBox chkFrenchFries;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JPanel pnlActions;
    private javax.swing.JPanel pnlBurger;
    private javax.swing.JPanel pnlDrink;
    private javax.swing.JPanel pnlOptions;
    // End of variables declaration//GEN-END:variables
}
